### ISSUE TITLE
Release file unable to open

### ISSUE THREAD

**Issue by NostalgiaNinja** [petras607/PPQCacheExtractor#1]
Several users on the Discord have received the issue: "The program can't start because MSVCP140D.dll is missing from your computer. try reinstalling the program to fix the problem."

If possible, please provide the dependencies (or a place for installing the dependencies to the system) in your project so that users will be able to use the application.

**Comment by petras607** [comment]
The program uses basic C++ so far with no other external libraries so far. I wrote the recommended redistributable in readme.

**Comment by petras607** [comment]
Now the issue is finally fixed by changing te runtime library options in Visual Studio to /MT, which will statically link any libraries into the exe.
